//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityOfLifePrediction.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QualityOfLife_StatisticsEntities : DbContext
    {
        public QualityOfLife_StatisticsEntities()
            : base("name=QualityOfLife_StatisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<DataModel> DataModels { get; set; }
        public virtual DbSet<DataSet> DataSets { get; set; }
        public virtual DbSet<DataSource> DataSources { get; set; }
        public virtual DbSet<ForecastData> ForecastDatas { get; set; }
        public virtual DbSet<ForecastDataSet> ForecastDataSets { get; set; }
        public virtual DbSet<ForecastFarness> ForecastFarnesses { get; set; }
        public virtual DbSet<ForecastingMethod> ForecastingMethods { get; set; }
        public virtual DbSet<IncomeGroup> IncomeGroups { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
